### ISSUE TITLE
2 features I see missing

### ISSUE THREAD

**Issue by lightningblaze** [grindhold/rainbow-lollipop#32]
Bookmarks - So we can save a page for easy access at any time. This will likely open a new track starting with that bookmarked page when its clicked

Proxy Support - Sometimes I find myself needing a proxy, be it required for the network or something I need is blocked, I would like a way to enter a proxy server to browse the network through instead of normal internet.

**Comment by grindhold** [comment]
Bookmarks - This is a matter of discussion, because it's not clear by now, whether we want to bookmark single pages in RL or Tracks as a whole. I think we have to implement both features and see how people react to it.

Proxy Support - as soon as I proceed to build the deepweb-related features, i must look into that anyway. For me the priority is to implement HTTPSEverywhere and Adblocking. Feel free to start implementing stuff that you need if you want.

P.S.: Don't hesitate to open two tickets. One Issue per Issue, so to say. That would be awesome ;)

**Comment by grindhold** [comment]
this issue has been splitted into #68 and #67
